apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tradmodels-pvc
  namespace: kafka-flink
spec:
  accessModes:
    - ReadWriteMany           # Set as needed (ReadWriteOnce, ReadOnlyMany, ReadWriteMany)
  resources:
    requests:
      storage: 100Gi          # Specify the amount of storage needed
  volumeMode: Filesystem      # Typically either Filesystem or Block
