apiVersion: v1
kind: PersistentVolume
metadata:
  name: tradmodels-pv
spec:
  capacity:
    storage: 100Gi # Adjust the size according to your needs
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /nfs/home/khurana/dataset-tradmodels/dataset/

  persistentVolumeReclaimPolicy: Retain
