apiVersion: batch/v1
kind: Job
metadata:
  name: tradmodels-job
  namespace: refit-release
spec:
  template:
    metadata:
      labels:
        app: tradmodels
    spec:
      nodeSelector:
         refit: enabled
      serviceAccountName: refit
      containers:
        - name: tradmodels
          image: ramankhurana/tradmodels:latest
          imagePullPolicy: Always
	  ## override the command in dockerfile
          command: ["/bin/sh", "-c"]  # Use shell to interpret the command
          args:
            - "python EvaluateModel.py --dataset=TEMPLATE_DATASET_NAME --model=TEMPLATE_MODEL_NAME"
          resources:
            requests:
              memory: "11Gi"
              cpu: "3"
            limits:
              memory: "12Gi"
              cpu: "4"
          volumeMounts:
            - name: dataset-volume
              mountPath: /mnt-gluster/all-data/khurana/dataset-tradmodels/dataset
            - name: config-volume
              mountPath: /usr/src/app/tradmodels/datasetschema.yaml
              subPath: datasetschema.yaml

      volumes:
        - name: dataset-volume
          persistentVolumeClaim:
            claimName: tradmodels-pvc

        - name: config-volume
          configMap:
            name: datasetschema-config

        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: "3Gi"
      restartPolicy: Never
  backoffLimit: 0
